default_language_version:
  python: python3.12


repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-toml
      - id: no-commit-to-branch
        args: [--branch, master]
      - id: end-of-file-fixer
        exclude: ".*\\.md"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        files: ".*\\.md"
        additional_dependencies:
          - mdformat-gfm
          - mdformat-ruff
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types_or: [python, pyi]
        require_serial: true
        args: [--install-types, --non-interactive]
