services:
  rabbit:
    image: rabbitmq:3-management
    container_name: text-classifier-rabbit
    networks:
      - net
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  api:
    container_name: text-classifier-api
    build:
      context: .
      target: runtime
    networks:
      - net
    ports:
      - "8000:8000"
    volumes:
      - ./hf_home:/app/hf_home
    environment:
      HF_HOME: "/app/hf_home/"
      TEXT_CLASSIFIER__RABBIT__URL: "amqp://rabbit:password@rabbit:5672/?heartbeat=180"
    depends_on:
      rabbit:
        condition: service_healthy

networks:
  net:
    name: text-classifier-network
